### PR TITLE
Fix ci

### PR DESCRIPTION
**Pull request by ghost**
Sorry I made a silly mistake in my haste, there is no space in the command `golint`.

### CODE REVIEW

**Comment by ghost** [comment]
oops, and have to add golint.. hold off on merging a minute

**Comment by ghost** [comment]
Ok, all set for review. Sorry again for the mistake @samber

**Comment by samber** [comment]
yes ! You're right ;)

Could you add some ` ./...` after build, golint, vet plz ?

**Comment by ghost** [comment]
Sure, one sec

**Pull request merged**
